### ISSUE TITLE
Chaining HTTPBackend with LocalStorageBackend

### ISSUE THREAD

**Issue by abhijit945** [i18next/i18next-chained-backend#13]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

Assume `System.resolve` resolves to `localhost:5000` via `@libra/ui`
```js
import ChainedBackend from 'i18next-chained-backend';
import HTTPBackend from 'i18next-http-backend';
import LocalStorageBackend from 'i18next-localstorage-backend';

  const loadPath = (language: string, namespace: string) =>
    // eslint-disable-next-line no-undef
    System.resolve(`@libra/ui/locales/${language}/${namespace}.json`);

  const instance = i18n.createInstance();

  instance
    .use(ChainedBackend)
    .use(initReactI18next)
    .init({
      supportedLngs: ['ja-jp'],
      fallbackLng: 'en-us',
      ns: ['translation'],
      react: {
        wait: true,
        useSuspense: false,
      },
      backend: {
        backends: [LocalStorageBackend, HTTPBackend],
        backendOptions: [{ loadPath }],
      },
      keySeparator: false,
      lowerCaseLng: true,
    });
```

## Expected behavior

There are 2 scenarios here: 

1. With **ChainedBackend + HTTPBackend + LocalStorageBackend** similar to [here](https://github.com/i18next/i18next-chained-backend#more-complete-sample)
The network request that are made are `http://localhost:8000/locales/ja-jp/translation.json` instead (resulting in **404**)

2. With **HTTPBackend** only: With following changes: 

```js
instance
    .use(HTTPBackend)
    .use(initReactI18next)
    .init({
        supportedLngs: ["ja-jp"],
        fallbackLng: "en-us",
        ns: ["translation"],
        react: {
            wait: true,
            useSuspense: false,
        },
        backend: {
            loadPath,
        },
        keySeparator: false,
        lowerCaseLng: true,
    });

```
Can confirm this works: `http://localhost:5000/locales/ja-jp/translation.json` with a satisfying **200 OK**! 

## Additional Debug information

For some reason the `loadPath` going into each plugin is different. The `loadPath` should be a function (which is only true to first plugin and not the second)

<img width="630" alt="Screen Shot 2020-07-01 at 2 08 08 PM" src="https://user-images.githubusercontent.com/4908886/86282358-aece2e80-bba4-11ea-80c4-30b2e31cbf45.png">
<img width="630" alt="Screen Shot 2020-07-01 at 2 08 22 PM" src="https://user-images.githubusercontent.com/4908886/86282362-b1308880-bba4-11ea-8eea-c0a5be093819.png">

## Your Environment

- *runtime version*: i.e. node v12, browser chrome
- *i18next version*: latest
- *os*: Mac

**Comment by jamuhl** [comment]
might be you should pass backendOptions correctly...`backendOptions: [{}, { loadPath }],`

**Comment by abhijit945** [comment]
Works! That does make sense! Thank you.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
