### ISSUE TITLE
TypeScript error triggered between `i18next-chained-backend` and `i18next-http-backend`

### ISSUE THREAD

**Issue by jdeniau** [i18next/i18next-chained-backend#22]
## 🐛 Bug Report

There is a conflict in the .d.ts files between i18next-chained-backend and i18next-http-backend

## To Reproduce

i18n config

```js
import i18n from 'i18next';
import ChainedBackend from 'i18next-chained-backend';
import HttpApi from 'i18next-http-backend';

const httpBackend = new HttpApi(null, {
  loadPath: '/somewhere'
});

i18n
  .use(ChainedBackend)
  .init({
    backend: {
      backends: [
        httpBackend,
       // fallback backend
      ],
    },
  });
```

## Current behavior

```
node_modules/i18next-http-backend/index.d.ts:122:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'backend' must be of type 'BackendOptions | undefined', but here has type 'BackendOptions | undefined'.

122     backend?: BackendOptions;
        ~~~~~~~

  node_modules/i18next-chained-backend/index.d.ts:42:5
    42     backend?: I18NextChainedBackend.BackendOptions;
           ~~~~~~~
    'backend' was also declared here.

```

## Expected behavior

No error

## Possible temporary fix

Setting `"skipLibCheck": true` hide the issue

## Your Environment

- typescript: 4.3.5
- i18next-chained-backend : 3.0.2
- i18next-http-backend: 1.3.0

**Comment by adrai** [comment]
did you set the skipLibCheck to true? https://github.com/i18next/i18next-chained-backend#typescript

**Comment by jdeniau** [comment]
@adrai Oh I didn't see that this is in the readme file 🤦 

As a matter of fact I did post the solution as a "temporary fix" in my issue.

It is something that is fixable that you did not managed to fix or is it by design ?

**Comment by adrai** [comment]
@pedrodurek maybe knows the detail?

**Comment by pedrodurek** [comment]
It's by design, that's the only way to automatically infer `PluginOptions` which happens to have conflicts with other plugins. `skipLibCheck: true` is also recommended to reduce compilation time.
