### ISSUE TITLE
how to call save method again in my custom plugin if it has saved data already first time??

### ISSUE THREAD

**Issue by sanjaysinghal7** [i18next/i18next-chained-backend#24]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by jamuhl** [comment]
Looks not like a bug - looks like a question or custom issue / lack of understanding

**Comment by jamuhl** [comment]
call `backend.save` with correct params as i18next would do on first time

**Comment by sanjaysinghal7** [comment]
Thanks jamuhl
