### ISSUE TITLE
Incompatible with fallbackLng

### ISSUE THREAD

**Issue by Maxim-Filimonov** [i18next/i18next-chained-backend#25]
## 🐛 Bug Report
I noticed that this backend is not compatible with `fallbackLng` property of i18n. 
It throws an exception despite the fact that `fallbackLng` is specified.

## To Reproduce

[Example](https://codesandbox.io/s/damp-snowflake-6q1yz4?file=/src/i18n.js)

## Expected behaviour

Expected to not throw warnings/errors when `fallbackLng` is present.

## Your Environment

- *runtime version*: node 14
- *i18next version*: i18next-chained-backend@3.0.2
- *os*: Mac, Windows, Mac
- *any other relevant information*

**Comment by adrai** [comment]
Your backend options are not correctly passed in the init function: https://codesandbox.io/s/billowing-wildflower-oyj715?file=/src/i18n.js:1836-1934

**Comment by jordanshardy** [comment]
@adrai thanks for the response here. When the backend options are correctly passed like this [example](https://codesandbox.io/s/naughty-hooks-rgw7x6?file=/src/i18n.js) it is still throwing a warning which I have attached below. Any help with this would be awesome. Thanks!

![Uploading Screen Shot 2022-03-01 at 10.40.40 am.png…]()

**Comment by adrai** [comment]
> 

Sorry, but I don't see that warning... I just see:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/1086194/156114579-ad38bd6d-7871-4f53-9218-7ef4790d5e5c.png">


btw: regarding saveMissing: https://github.com/i18next/i18next-chained-backend#important-advice-for-the-usage-in-combination-with-savemissingupdatemissing
