### ISSUE TITLE
Type 'ChainedBackendOptions' has no properties in common with type 'InitOptions<unknown>'

### ISSUE THREAD

**Issue by laclance** [i18next/i18next-chained-backend#29]
After updating packages I cannot get rid of typescipt errors. I copied the example from the docs.
If I remove the `<ChainedBackendOptions>` then it says 'backends' does not exist in type 'LocizeBackendOptions'.

```js
import i18next from 'i18next';
import { initReactI18next } from 'react-i18next';
import ChainedBackend, { ChainedBackendOptions } from 'i18next-chained-backend';
import LocizeBackend from 'i18next-locize-backend';
import HTTPBackendLocal from 'i18next-http-backend';
import pos from 'pos.json';

export const defaultNS = 'pos';
export const resources = {
  en: {
    pos
  }
} as const;

i18next
  .use(initReactI18next)
  .use(ChainedBackend)
  .init(<ChainedBackendOptions>{
    backend: {
      backends: [
        LocizeBackend, // primary
        HTTPBackendLocal // fallback
      ],
      backendOptions: [
        {
          projectId: 'myLocizeProjectId'
        },
        {
          loadPath: '/locales/{{lng}}/{{ns}}.json' // http api load path for my own fallback
        }
      ]
    },
    fallbackLng: 'en',
    fallbackNS: 'pos',
    defaultNS: 'pos',
    ns: ['pos'],
    interpolation: {
      escapeValue: false
    }
  });

export default i18next;
```

- *runtime version*: i.e. node v14.20, chrome
- *os*: windows
    "i18next": "^22.4.6",
    "i18next-chained-backend": "^4.2.0",
    "i18next-http-backend": "^2.1.1",
    "i18next-locize-backend": "^6.0.0",

**Comment by adrai** [comment]
Make sure you've updated all i18next dependencies.
If the problem still persists, create a minimal reproducible repository or similar please.

**Comment by adrai** [comment]
make sure you've installed v6.1.1 of i18next-locize-backend

**Comment by adrai** [comment]
seems to work: https://github.com/i18next/i18next-chained-backend/blob/master/test/typescript/basic.test-d.ts

**Comment by laclance** [comment]
thank you, yarn did not update to v6.1.1
