### ISSUE TITLE
Cannot create property 'i18nStamp' on boolean 'true'

### ISSUE THREAD

**Issue by ljosberinn** [i18next/i18next-chained-backend#9]
Noticed this when Netlify Webhooks send a notification to a Discord channel. Discord will visit the site to fetch graph metadata, using Headless Chrome.

This leads to requesting the translation from the backend, which (sometimes) fails; that's something else I'm looking into. XHR-Backend [returns true as `data`](https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L53) which leads to [chained-backend](https://github.com/i18next/i18next-chained-backend/blob/master/src/index.js#L35) triggering the save-callback because JS thinks `Object.keys(true).length > -1 === true` is fine.

So probably,
```js
if (data && Object.keys(data).length > -1) {
```
should be
```js
if(data && data !== true && Object.keys(data).length > -1) {
```

Happy to create a PR if this is fine.

**Comment by jamuhl** [comment]
Arghh...right....`if (!err && data && Object.keys(data).length > -1) {` should do the trick...if you like I would happy accept a PR...else I will try to add this sometime next week
